# Generated by Django 4.1.5 on 2023-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
